---
kind: pipeline
type: docker
trigger:
  ref:
    - refs/heads/master
    - refs/pull/**
    - refs/tags/*
steps:
  - name: install
    image: node
    commands:
      - npm ci
  - name: lint
    image: node
    commands:
      - npm run lint
  - name: publish
    image: node
    when:
      status:
        - success
      event:
        - tag
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - npm set registry https://registry.npmjs.org
      - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - npm publish
---
kind: signature
hmac: 3a29b9e93b6407682840217ee2271d9438130c222dacf31f306bc17ebca4026e

...
